filebeat.inputs:

- type: log
  enabled: true
  paths:
  - /usr/share/filebeat/mylog/*.log #需要讀取日誌的目錄#
  tags: ["test"]

  json.keys_under_root: true
  json.add_error_key: true
  json.overwrite_keys: true

# 直接輸出到elasticsearch,這裏的hosts是elk地址，port是elasticsearch port#
# output.elasticsearch:
#   hosts: ["10.144.187.150:9200"]

output.logstash:
  hosts: ["logstash:5044"]

# output.file:     #输出到文件
#   path: "/usr/share/filebeat/data"
#   filename: "filebeat_test.txt" 

# output.file:
#   # Boolean flag to enable or disable the output module.
#   enabled: true
    
#   # Path to the directory where to save the generated files. The option is
#   # mandatory.
#   path: /usr/share/filebeat/data/filebeatLogs
    
#   # Name of the generated files. The default is `filebeat` and it generates
#   # files: `filebeat`, `filebeat.1`, `filebeat.2`, etc.
#   filename: filebeat
    
#   # Maximum size in kilobytes of each file. When this size is reached, and on
#   # every filebeat restart, the files are rotated. The default value is 10240
#   # kB.
#   #rotate_every_kb: 10000
    
#   # Maximum number of files under path. When this number of files is reached,
#   # the oldest file is deleted and the rest are shifted from last to first. The
#   # default is 7 files.
#   number_of_files: 7